# Generated by Django 3.1.5 on 2021-02-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_img',
            new_name='picture',
        ),
    ]
