export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTHENTICATION_SUCCESS = 'CHECK_AUTHENTICATION_SUCCESS';
export const CHECK_AUTHENTICATION_FAIL = 'CHECK_AUTHENTICATION_FAIL';

export const FETCH_HOUSING_LIST = 'FETCH_HOUSING_LIST';
export const FETCH_MY_HOUSING_LISTINGS = 'FETCH_MY_HOUSING_LISTINGS';
export const FILTER_HOUSING_LIST = 'FILTER_HOUSING_LIST';
export const FETCH_SAVED_HOUSING = 'FETCH_SAVED_HOUSING';
export const SAVE_HOUSING = 'SAVE_HOUSING';
export const UNSAVE_HOUSING = 'UNSAVE_HOUSING';
export const SET_FILTERS = 'SET_FILTERS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
