# Generated by Django 3.1.5 on 2021-02-01 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('street_address_is_open', models.BooleanField(default=True)),
                ('zipcode', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rent_start_date', models.DateField()),
                ('rent_end_date', models.DateField()),
                ('room_type', models.CharField(choices=[('Studio', 'Studio'), ('1 Bedroom', 'One Bed'), ('2 Bedroom', 'Two Bed'), ('3 Bedroom', 'Three Bed'), ('Entire House', 'Entire House')], max_length=100)),
                ('roommates', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('is_negotiable', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('campus_area', models.CharField(choices=[('North Campus', 'North'), ('Mid Campus', 'Mid'), ('South Campus', 'South')], max_length=20)),
                ('duration_tech', models.CharField(default=0, max_length=20)),
                ('duration_norris', models.CharField(default=0, max_length=20)),
                ('duration_kresge', models.CharField(default=0, max_length=20)),
                ('duration_target', models.CharField(default=0, max_length=20)),
                ('image_main', models.ImageField(upload_to='housing_pics')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_9', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('image_10', models.ImageField(blank=True, null=True, upload_to='housing_pics')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
