# Generated by Django 3.1.5 on 2021-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='room_type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1 Bedroom', 'One Bed'), ('2 Bedroom', 'Two Bed'), ('3 Bedroom', 'Three Bed'), ('4 Bedroom', 'Four Bed'), ('5 Bedroom', 'Five Bed')], max_length=100),
        ),
    ]
