# Generated by Django 3.1.5 on 2021-02-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20210204_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='image_9',
        ),
        migrations.CreateModel(
            name='HousingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='housing_pics')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='housing.housing')),
            ],
        ),
    ]
