# Generated by Django 3.1.5 on 2021-02-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20210211_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingimage',
            old_name='photo',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='housingimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.housing'),
        ),
    ]
