# Generated by Django 3.1.5 on 2021-02-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_auto_20210213_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.housing'),
        ),
    ]
