# Generated by Django 3.1.5 on 2021-02-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_auto_20210213_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingimage',
            old_name='image_url',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='housingimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.housing'),
        ),
    ]
