# Generated by Django 3.1.5 on 2021-02-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_auto_20210214_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingimage',
            old_name='post',
            new_name='housing',
        ),
    ]
