# Generated by Django 3.1.5 on 2021-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_auto_20210214_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='is_lgbtq_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housing',
            name='is_pet_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_class', models.CharField(max_length=50)),
                ('housing', models.ManyToManyField(blank=True, related_name='amenities', to='housing.Housing')),
            ],
        ),
    ]
