# Generated by Django 3.1.5 on 2021-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_auto_20210215_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='housing',
        ),
        migrations.AddField(
            model_name='housing',
            name='amenities',
            field=models.ManyToManyField(to='housing.Amenity'),
        ),
    ]
