# Generated by Django 3.1.5 on 2021-02-15 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0010_auto_20210215_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
