# Generated by Django 3.1.5 on 2021-02-17 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0011_housing_bookmarked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='housing.Amenity'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
    ]
