# Generated by Django 3.1.5 on 2021-02-17 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0012_auto_20210217_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='bookmarked_by',
        ),
        migrations.AddField(
            model_name='housing',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
