# Generated by Django 3.1.5 on 2021-03-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0013_auto_20210217_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='image_main',
        ),
    ]
