# Generated by Django 3.1.5 on 2021-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0014_remove_housing_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
